#config_version=6
##! mode: delivery_manager

mode:
    start_events: ball_started, mode_slurm_factory_stopped, mode_cryolab_delivery_stopped
    stop_events: found_golden_cap, ball_ending, mode_cryolab_delivery_started
    priority: 102

state_machines:
    fuel_gauge_state:
        persist_state: true
        states:
            start:
                label: Start state
                events_when_started: empty_tank
            quarter:
                events_when_started: quarter_tank
            half:
                events_when_started: half_tank
            3quarter:
                events_when_started: 3quarter_tank
            full:
                events_when_started: full_tank
        transitions:
            - source: start
              target: quarter
              events: collect_dark_matter_fuel_hit
            - source: quarter
              target: half
              events: collect_dark_matter_fuel_hit
            - source: half
              target: 3quarter
              events: collect_dark_matter_fuel_hit
            - source: 3quarter
              target: full
              events: collect_dark_matter_fuel_hit
            - source: full
              target: 3quarter
              events: use_dark_matter
            - source: 3quarter
              target: half
              events: use_dark_matter
            - source: half
              target: quarter
              events: use_dark_matter
            - source: quarter
              target: start
              events: use_dark_matter
            - source: half
              target: start
              events: use_half_tank
            - source: 3quarter
              target: quarter
              events: use_half_tank
            - source: full
              target: half
              events: use_half_tank
    next_delivery:
        persist_state: true
        states:
            start:
                label: Start state
                events_when_started: set_next_delivery_moon
            cannibalon:
                events_when_started: set_next_delivery_cannibalon
            trisol:
                events_when_started: set_next_delivery_trisol
            robot_homeworld:
                events_when_started: set_next_delivery_robot_homeworld
            roswell:
                events_when_started: set_next_delivery_roswell
        transitions:
            - source: start
              target: cannibalon
              events: moon_delivery_done
            - source: cannibalon
              target: trisol
              events: stop_cannibalon_delivery_mode
            - source: trisol
              target: robot_homeworld
              events: stop_trisol_delivery_mode
            - source: robot_homeworld
              target: roswell
              events: stop_robot_homeworld_delivery_mode
    moon_delivery_handler:
        persist_state: true
        states:
            start:
                label: Start state
            moon_delivery_enable:
                events_when_started: moon_delivery_lit
            moon_delivery_active:
                events_when_started: moon_delivery_active
            moon_delivery_done:
                events_when_started: moon_delivery_done
        transitions:
            - source: start
              target: moon_delivery_enable
              events: half_tank
            - source: moon_delivery_enable
              target: moon_delivery_active
              events: start_moon_delivery_mode
            - source: moon_delivery_active
              target: moon_delivery_done
              events: mode_moon_delivery_stopped
    cannibalon_delivery_handler:
        persist_state: true
        states:
            start:
                label: Start state
            cannibalon_delivery_next:
                events_when_started: cannibalon_delivery_next
            cannibalon_delivery_enable:
                events_when_started: cannibalon_delivery_lit
            cannibalon_delivery_active:
                events_when_started: cannibalon_delivery_active
            cannibalon_delivery_done:
                events_when_started: cannibalon_delivery_done
        transitions:
            - source: start
              target: cannibalon_delivery_next
              events: set_next_delivery_cannibalon
            - source: cannibalon_delivery_next
              target: cannibalon_delivery_enable
              events: half_tank, 3quarter_tank, full_tank
            - source: cannibalon_delivery_enable
              target: cannibalon_delivery_active
              events: cannibalon_delivery_start_shot_hit
            - source: cannibalon_delivery_active
              target: cannibalon_delivery_done
              events: cannibalon_delivery_show_ended

widgets:
    cannibalon_delivery_video:
        - type: video
          video: cannibalon_delivery_clip
          z: 10

shots:
    collect_dark_matter_fuel:
        switch: s_right_ramp
        enable_events: mode_delivery_manager_started, mode_moon_delivery_stopped
        disable_events: mode_moon_delivery_started
        hit_events: s_dt_nibbler_active
    moon_delivery_start_shot:
        switch: s_VUK
        enable_events: moon_delivery_lit
        disable_events: mode_moon_delivery_started
        persist_enable: true
    cannibalon_delivery_start_shot:
        switch: s_VUK
        enable_events: cannibalon_delivery_lit
        disable_events: cannibalon_delivery_show_ended
        persist_enable: true

ball_holds:
    cannibalon_delivery_hold:
        balls_to_hold: 1
        hold_devices: bd_VUK
        enable_events: cannibalon_delivery_lit
        disable_events: cannibalon_delivery_show_ended
        release_one_events: cannibalon_delivery_show_ended
        debug: true
    moon_delivery_start_hold:
        balls_to_hold: 1
        hold_devices: bd_VUK
        enable_events: moon_delivery_lit
        disable_events: moon_delivery_intro_show_ended
        release_one_events: moon_delivery_intro_show_ended
        debug: true

slide_player:
    mode_moon_delivery_started:
        base_slide:
            action: remove
        moon_delivery_slide:
            action: play
            target: display1
    mode_moon_delivery_stopped:
        base_slide:
            action: play
            target: display1
        moon_delivery_slide:
            action: remove

widget_player:
    mode_moon_delivery_stopped:
        full_gauge:
            slide: base_slide
            action: remove
        3quarter_gauge:
            slide: base_slide
            action: remove
        half_gauge:
            slide: base_slide
            action: remove
        quarter_gauge:
            slide: base_slide
            action: remove
    cannibalon_delivery_show_ended:
        full_gauge:
            slide: base_slide
            action: remove
        3quarter_gauge:
            slide: base_slide
            action: remove
        half_gauge:
            slide: base_slide
            action: remove
        quarter_gauge:
            slide: base_slide
            action: remove

variable_player:
    cannibalon_delivery_start_shot_hit:
        score: 5000
        deliveries_completed: 1

sound_player:
    quarter_tank:
        ding:
            action: play
    half_tank:
        ding:
            action: play
    3quarter_tank:
        ding:
            action: play
    full_tank:
        ding:
            action: play
    delivery_started:
        theme_full:
            action: stop
    mode_moon_delivery_stopped:
        old_moon_song:
            action: stop
    delivery_ended:
        theme_full:
            action: play

event_player:
    moon_delivery_start_shot_hit: start_moon_delivery_mode
    start_moon_delivery_mode: delivery_started
    mode_moon_delivery_stopped: use_half_tank, delivery_ended
    cannibalon_delivery_start_shot_hit: delivery_started
    cannibalon_delivery_show_ended: use_half_tank, delivery_ended

show_player:
    mode_moon_delivery_started:
        moon_delivery_intro_show:
            loops: 0
            priority: 500
            events_when_stopped: moon_delivery_intro_show_ended
    cannibalon_delivery_start_shot_hit:
        cannibalon_delivery_show:
            loops: 0
            priority: 500
            events_when_stopped: cannibalon_delivery_show_ended
        delivery_lit_show: stop
    moon_delivery_lit:
        delivery_lit_show:
            loops: -1
    moon_delivery_start_shot_hit:
        delivery_lit_show: stop
    cannibalon_delivery_lit:
        delivery_lit_show:
            loops: -1
