#config_version=6
##! mode: robot_homeworld_delivery

mode:
    start_events: start_robot_homeworld_delivery
    stop_events: stop_robot_homeworld_delivery
    priority: 200

state_machines:
    robot_homeworld_delivery_state:
        persist_state: false
        states:
            start:
                label: Start state
                events_when_started: robot_homeworld_delivery_waiting
            lower_bender:
                events_when_started: lower_bender_with_winch
            dress_up:
                events_when_started: dress_up_like_robots
            infiltrate:
                events_when_started: infiltrate_robot_city
            human_hunt:
                events_when_started: human_hunt_begins
            find_bender:
                events_when_started: try_rescue_bender
            robot_elders:
                events_when_started: robot_elders
            escape:
                events_when_started: escape_robot_city
            deliver_lugnuts:
                events_when_started: deliver_lugnuts
        transitions:
            - source: start
              target: lower_bender
              events: robot_homeworld_intro_done
            - source: lower_bender
              target: dress_up
              events: bender_captured
            - source: dress_up
              target: infiltrate
              events: done_dressing_up
            - source: infiltrate
              target: human_hunt
              events: let_the_human_hunt_begin
            - source: human_hunt
              target: find_bender
              events: found_bender
            - source: find_bender
              target: robot_elders
              events: found_bender_got_caught
#skip to robot_elders if you fail infiltrate or human_hunt
            - source: infiltrate
              target: robot_elders
              events: infiltrate_failed
            - source: human_hunt
              target: robot_elders
              events: human_hunt_failed
            - source: robot_elders
              target: escape
              events: escape_robot_elders
            - source: escape
              target: deliver_lugnuts
              events: drop_package_on_robots

slides:
#use main_delivery_slide (in config) for main UI
    RH_delivery_instructions_slide:
        widgets:
            - type: image
              image: RH_delivery_instructions_BG

slide_player:
#setup main UI on mode start
#call PF display slides
    robot_homeworld_intro_done:
        main_delivery_slide:
            target: display1
            priority: 1
        RH_delivery_instructions_slide:
            target: display2


widgets:
#use the normal UI widgets + mode specific background and videos listed here
#list widgets for PF display

widget_player:
#most of this is done in shows, usually not much here



shots:
#make sure to have blocking shots for all bose mode shots that aren't disabled
#by crew_manager being paused why in delivery modes
    lower_winch_shot:
        switches: s_pe_platter
        enable_events: lower_bender_with_winch
        disable_events: ball_ending, timer_lower_bender_timer_complete


timers:
    lower_bender_timer:
        start_value: 30
        end_value: 0
        direction: down
        control_events:
            - action: start
              event: lower_bender_with_winch
            - action: stop
              event: ball_ending
    
event_player:

show_player:
#shows should be started by events generated by state machine changes and
#stopped by shots being completed or timers completing
#all shows should explicitly stop if the ball drains
#all shows should start by ending other shows they might be interrupting

variable_player:
#scoring and setting variables for completing or failing the mode, etc.
