#config_version=6
##! mode: robot_homeworld_delivery

mode:
    start_events: start_robot_homeworld_delivery
    stop_events: stop_robot_homeworld_delivery
    priority: 200

state_machines:
    robot_homeworld_delivery_state:
        persist_state: false
        states:
            start:
                label: Start state
                events_when_started: robot_homeworld_delivery_waiting
            lower_bender:
                events_when_started: lower_bender_with_winch
            dress_up:
                events_when_started: dress_up_like_robots
            infiltrate:
                events_when_started: infiltrate_robot_city
            human_hunt:
                events_when_started: human_hunt_begins
            find_bender:
                events_when_started: try_rescue_bender
            robot_elders:
                events_when_started: robot_elders
            escape:
                events_when_started: escape_robot_city
            deliver_lugnuts:
                events_when_started: deliver_lugnuts
        transitions:
            - source: start
              target: lower_bender
              events: robot_homeworld_intro_done
            - source: lower_bender
              target: dress_up
              events: bender_captured
            - source: dress_up
              target: infiltrate
              events: done_dressing_up
            - source: infiltrate
              target: human_hunt
              events: infiltrate_combo_shot_hit
            - source: human_hunt
              target: find_bender
              events: found_bender
            - source: find_bender
              target: robot_elders
              events: found_bender_got_caught
#skip to robot_elders if you fail infiltrate or human_hunt
            - source: infiltrate
              target: robot_elders
              events: infiltrate_failed
            - source: human_hunt
              target: robot_elders
              events: human_hunt_failed
            - source: robot_elders
              target: escape
              events: escape_robot_elders
            - source: escape
              target: deliver_lugnuts
              events: drop_package_on_robots

slides:
#use main_delivery_slide (in config) for main UI
    RH_delivery_instructions_slide:
        widgets:
            - type: image
              image: RH_delivery_instructions_BG
        target: display2

slide_player:
#setup main UI on mode start
#call PF display slides
    mode_robot_homeworld_delivery_started:
        reusable_delivery_slide:
            target: display1
            priority: 1
        RH_delivery_instructions_slide:
            target: display2


widgets:
#use the normal UI widgets + mode specific background and videos listed here
#list widgets for PF display
#z values:
#    background image = 1
#    video clips = 3
#    UI = 5
#    text and numbers = 7
    ship_w_lowered_winch_BG:
        type: image
        image: PE_ship_winch_lowered
        z: 1


widget_player:
#most of this is done in shows, usually not much here



shots:
#make sure to have blocking shots for all bose mode shots that aren't disabled
#by crew_manager being paused why in delivery modes
    lower_winch_shot:
        switches: s_pe_platter
        enable_events: lower_bender_with_winch
        disable_events: ball_ending, timer_lower_bender_timer_complete, timer_lower_bender_timer_stopped
    dress_fry_like_robot_shot:
        switches: s_t_fry
        enable_events: dress_up_like_robots
        disable_events: timer_dress_up_timer_complete, timer_dress_up_timer_stopped, dress_fry_like_robot_shot_hit
    dress_leela_like_robot_shot:
        switches: s_t_leela
        enable_events: dress_up_like_robots
        disable_events: timer_dress_up_timer_complete, timer_dress_up_timer_stopped, dress_leela_like_robot_shot_hit
    left_ramp_infiltrate_shot:
        switches: s_right_ramp
        enable_events: infiltrate_robot_city
        disable_events: left_ramp_infiltrate_shot_hit
    right_loop_infiltrate_shot:
        switches: s_right_loop
        enable_events: infiltrate_robot_city
        disable_events: infiltrate_combo_shot_hit
    right_ramp_infiltrate_shot:
        switches: s_right_ramp
        enable_events: infiltrate_robot_city
        disable_events: infiltrate_combo_shot_hit
    right_orbit_infiltrate_shot:
        switches: s_r_orbit
        enable_events: infiltrate_robot_city
        disable_events: infiltrate_combo_shot_hit
    robot_city_tetris_shot:
        switches: s_VUK
        enable_events: human_hunt_begins
        disable_events: robot_elders


sequences:
    dress_both_like_robots_sequence:
        enable_events: dress_up_like_robots
        events:
            - dress_fry_like_robot_shot_hit, dress_leela_like_robot_shot_hit
            - dress_fry_like_robot_shot_hit, dress_leela_like_robot_shot_hit
        events_when_hit: beep_boop
        events_when_complete: done_dressing_up
        disable_events: done_dressing_up
    infiltrate_combo_shot:
        enable_events: infiltrate_robot_city
        events:
            - left_ramp_infiltrate_shot_hit
            - right_loop_infiltrate_shot_hit, right_orbit_infiltrate_shot_hit, right_ramp_infiltrate_shot_hit
        events_when_complete: infiltrate_combo_shot_hit
        disable_events: infiltrate_combo_shot_hit

timers:
    lower_bender_timer:
        start_value: 30
        end_value: 0
        direction: down
        control_events:
            - action: start
              event: lower_bender_with_winch
            - action: stop
              event: ball_ending
    dress_up_timer:
        start_value: 20
        end_value: 0
        direction: down
        control_events:
            - action: start
              event: dress_up_like_robots
            - action: stop
              event: done_dressing_up
    infiltrate_robot_city_timer:
        start_value: 30
        end_value: 0
        direction: down
        control_events:
            - action: start
              event: infiltrate_robot_city
            - action: stop
              event: infiltrate_combo_shot_hit
    human_hunt_timer:
        start_value: 30
        end_value: 0
        direction: down
        control_events:
            - action:
              event: let_the_human_hunt_begin
            - action: stop
              event: found_bender
            - action: stop
              event: robot_city_tetris_shot_hit
            - action: restart
              event: robot_city_tetris_release
event_player:
    timer_infiltrate_robot_city_timer_complete: infiltrate_failed


show_player:
#shows should be started by events generated by state machine changes and
#stopped by shots being completed or timers completing
#all shows should explicitly stop if the ball drains
#all shows should start by ending other shows they might be interrupting
    mode_robot_homeworld_delivery_started:
        robot_homeworld_delivery_intro_show:
            loops: 0
            action: play
            events_when_stopped: robot_homeworld_intro_done
    flipper_cradle:
        robot_homeworld_delivery_intro_show: stop
    lower_bender_with_winch:
        lower_bender_with_winch_show:
            loops: 0
            action: play
    dress_up_like_robots:
        dress_up_like_robots_show:
            loops: 0
            action: play
    done_dressing_up:
        dress_up_like_robots_show:
            action: stop
    infiltrate_robot_city:
        infiltrate_robot_city_show:
            loops: 0
            action: play
    infiltrate_combo_shot_hit:
        infiltrate_robot_city_show:
            action: stop


variable_player:
#scoring and setting variables for completing or failing the mode, etc.
    lower_winch_shot_hit:
        score: machine.ship_points * current_player.crew_multiplier * bender_multiplier
    dress_fry_like_robot_shot_hit:
        score: machine.target_points * current_player.fry_multiplier * bender_multiplier
    dress_leela_like_robot_shot_hit:
        score: machine.target_points * current_player.leela_multiplier * bender_multiplier
    left_ramp_infiltrate_shot_hit:
        score: machine.ramp_points * 5 * current_player.fry_multiplier
    infiltrate_combo_shot_hit:
        score: machine.ramp_points * 10 * current_player.leela_multiplier
