#config_version=6
##! mode: moon_delivery

mode:
    start_events: start_moon_delivery_mode
    stop_events: stop_moon_delivery_mode, ball_ending
    priority: 200

state_machines:
    moon_delivery_state:
        persist_state: false
        states:
            start:
                label: Start state
                events_when_started: moon_delivery_waiting
#move to step1 when the intro video stops
            step1:
                events_when_started: moon_delivery_step1
#shoot the right orbit to delivery the crate and progress to step2
            step2:
                events_when_started: moon_delivery_step2
#shoot whalers_shots twice to progress to step3
            step3:
                events_when_started: moon_delivery_step3
            step4:
                events_when_started: moon_delivery_step4
            step5:
                events_when_started: moon_delivery_step5
            step6:
                events_when_started: moon_delivery_step6
            steps_complete:
                events_when_started: moon_delivery_steps_complete
            failed:
                events_when_started: moon_delivery_failed
        transitions:
            - source: start
              target: step1
              events: moon_delivery_intro_show_ended
            - source: step1
              target: step2
              events: crate_delivered_show_ended
            - source: step2
              target: step3
              events: rode_whalers
            - source: step3
              target: step4
              events: rover_escape_show_ended
            - source: step4
              target: step5
              events: timer_joyride_timer_complete
            - source: step5
              target: step6
              events: farmer_escape_show_ended
            - source: step6
              target: steps_complete
              events: lander_found
            - source: start, step2, step3, step4, step5, step6
              target: failed
              events: fail_moon_delivery
    whalers_state:
#need this to play the whalers_song clips in order
        persist_state: false
        states:
            start:
                label: Start state
                events_when_started: whalers_shot_waiting
            play_first_whalers:
                events_when_started: play_first_whalers
            play_second_whalers:
                events_when_started: play_second_whalers
        transitions:
            - source: start
              target: play_first_whalers
              events: sing_a_whaling_tune
            - source: play_first_whalers
              target: play_second_whalers
              events: sing_a_whaling_tune

# TODO: needs update for config_version=6
light_player:
    moon_delivery_waiting:
        loops: ffffff
        l_delivery_shot_insert: ffffff
        l_right_ramp_insert: ffffff
        l_right_corner1: ffffff
ball_holds:
    final_scene_hold:
        balls_to_hold: 1
        hold_devices: bd_VUK
        enable_events: lunar_lander_found_shot_lit
        disable_events: stop_moon_delivery_mode, moon_delivery_success_show_ended
        release_one_events: stop_moon_delivery_mode, moon_delivery_success_show_ended

timers:
    crate_delivery_timer:
        start_value: 30
        end_value: 0
        direction: down
        control_events:
            - action: start
              event: moon_delivery_step1
            - action: stop
              event: deliver_crate_shot_hit
    whalers_on_the_moon_timer:
        start_value: 15
        max_value: 10
        end_value: 0
        direction: down
        control_events:
            - action: start
              event: moon_delivery_step2
            - action: add
              event: whalers_right_shot_hit
              value: 5
            - action: add
              event: whalers_left_shot_hit
              value: 5
            - action: stop
              event: rode_whalers
    lunar_rover_timer:
        start_value: 25
        end_value: 0
        direction: down
        control_events:
            - action: start
              event: moon_delivery_step3
            - action: stop
              event: rover_escape_shot_hit
    joyride_timer:
        start_value: 27
        end_value: 0
        direction: down
        control_events:
            - action: start
              event: moon_delivery_step4
    escape_farmer_timer:
        start_value: 32
        end_value: 0
        direction: down
        control_events:
            - action: start
              event: moon_delivery_step5
            - action: stop
              event: all_farmer_escape
    lunar_lander_timer:
        start_value: 20
        end_value: 0
        direction: down
        control_events:
            - action: start
              event: moon_delivery_step6
            - action: stop
              event: lunar_lander_found_shot_lit
            - action: add
              event: lunar_lander_l_shot_hit
              value: 5
            - action: add
              event: lunar_lander_r_shot_hit
              value: 5
    lunar_lander_found_timer:
        start_value: 10
        end_value: 0
        direction: down
        control_events:
            - action: start
              event: lunar_lander_found_shot_lit
            - action: stop
              event: lunar_lander_found_shot_hit


shots:
    deliver_crate_shot:
        switch: s_r_orbit
        enable_events: timer_crate_delivery_timer_started
        disable_events: timer_crate_delivery_timer_complete, timer_crate_delivery_timer_stopped
    whalers_left_shot:
        switch: s_left_loop
        enable_events: timer_whalers_on_the_moon_timer_started
        disable_events: timer_whalers_on_the_moon_timer_complete, timer_whalers_on_the_moon_timer_stopped
        delay_switch:
            s_right_loop: 2s
    whalers_right_shot:
        switch: s_right_loop
        enable_events: timer_whalers_on_the_moon_timer_started
        disable_events: timer_whalers_on_the_moon_timer_complete, timer_whalers_on_the_moon_timer_stopped
        delay_switch:
            s_left_loop: 2s
    rover_escape_shot:
        switch: s_right_ramp
        enable_events: timer_lunar_rover_timer_started
        disable_events: timer_lunar_rover_timer_complete, timer_lunar_rover_timer_stopped
    joyride_platter_shot:
        switch: s_pe_platter
        enable_events: timer_joyride_timer_started
        disable_events: timer_joyride_timer_complete
    bender_farmer_escape_shot:
        switch: s_t_bender
        enable_events: timer_escape_farmer_timer_started
        disable_events: timer_escape_farmer_timer_complete, bender_farmer_escape_shot_hit
    leela_farmer_escape_shot:
        switch: s_t_leela
        enable_events: timer_escape_farmer_timer_started
        disable_events: timer_escape_farmer_timer_complete, leela_farmer_escape_shot_hit
    fry_farmer_escape_shot:
        switch: s_t_fry
        enable_events: timer_escape_farmer_timer_started
        disable_events: timer_escape_farmer_timer_complete, fry_farmer_escape_shot_hit
    lunar_lander_l_shot:
        switch: s_left_ramp
        enable_events: timer_lunar_lander_timer_started
        disable_events: timer_lunar_lander_timer_stopped, lunar_lander_l_shot_hit
    lunar_lander_r_shot:
        switch: s_right_ramp
        enable_events: timer_lunar_lander_timer_started
        disable_events: timer_lunar_lander_timer_stopped, lunar_lander_r_shot_hit
    lunar_lander_found_shot:
        switch: s_VUK
        enable_events: timer_lunar_lander_found_timer_started
        disable_events: timer_lunar_lander_found_timer_stopped, lunar_lander_found_shot_hit

sequences:
    whalers_sequence:
        enable_events: timer_whalers_on_the_moon_timer_started
        events:
            - whalers_right_shot_hit, whalers_left_shot_hit
            - whalers_right_shot_hit, whalers_left_shot_hit
        events_when_hit: sing_a_whaling_tune
        events_when_complete: rode_whalers
    all_farmer_escape_sequence:
        enable_events: moon_delivery_step5
        events:
            - fry_farmer_escape_shot_hit, leela_farmer_escape_shot_hit, bender_farmer_escape_shot_hit
            - fry_farmer_escape_shot_hit, leela_farmer_escape_shot_hit, bender_farmer_escape_shot_hit
            - fry_farmer_escape_shot_hit, leela_farmer_escape_shot_hit, bender_farmer_escape_shot_hit
        events_when_complete: all_farmer_escape

    lunar_lander_search_sequence:
        enable_events: moon_delivery_step6
        events:
            - lunar_lander_searching
            - lunar_lander_searching
        events_when_complete: lunar_lander_found_shot_lit

slide_player:
    mode_moon_delivery_started:
        base_slide:
            action: remove
        moon_delivery_slide:
            action: play
            target: display1
    mode_moon_delivery_stopping:
        moon_delivery_slide:
            action: remove

widget_player:
    moon_delivery_step1:
        moon_step1:
            slide: moon_delivery_slide
        luna_park_background:
            slide: moon_delivery_slide
    moon_delivery_step2:
        moon_step1:
            action: remove
        moon_step2:
            slide: moon_delivery_slide
        whalers_background:
            slide: moon_delivery_slide
        luna_park_background:
            action: remove
    moon_delivery_step3:
        moon_step2:
            action: remove
        whalers_background:
            action: remove
        rover_background:
            slide: moon_delivery_slide
        moon_step3:
            slide: moon_delivery_slide
    rover_escape_shot_hit:
        rover_background:
            action: remove
    moon_delivery_step4:
        moon_step3:
            action: remove
        rover_background:
            action: remove
        joyride_background:
            slide: moon_delivery_slide
        moon_step4:
            slide: moon_delivery_slide
    moon_delivery_step5:
        moon_step4:
            action: remove
        joyride_background:
            action: remove
        farmer_background:
            slide: moon_delivery_slide
        moon_step5:
            slide: moon_delivery_slide
    all_farmer_escape:
        farmer_background:
            action: remove
    moon_delivery_step6:
        moon_step5:
            action: remove
        farmer_background:
            action: remove
        lander_background:
            slide: moon_delivery_slide
        moon_step6:
            slide: moon_delivery_slide
    lunar_lander_found_shot_lit:
        lander_background:
            action: remove
        lander_found_background:
            slide: moon_delivery_slide
    lunar_lander_found_shot_hit:
        lander_found_background:
            action: remove
    moon_delivery_steps_complete:
        moon_step6:
            action: remove
        moon_steps_complete:
            slide: moon_delivery_slide

variable_player:
    deliver_crate_shot_hit:
        moon_delivery_status:
            string: success
            action: set
        deliveries_completed: 1
        score: 2000
    fail_moon_delivery:
        moon_delivery_status:
            string: "fail"
            action: set
    whalers_right_shot_hit:
        score: 1000
    whalers_left_shot_hit:
        score: 1000
    rover_escape_shot_hit:
        score: 5000
    joyride_platter_shot_hit:
        score: 250 * current_player.fry_multiplier * current_player.leela_multiplier
    bender_farmer_escape_shot_hit:
        score: 2000 * current_player.bender_multiplier
    fry_farmer_escape_shot_hit:
        score: 2000 * current_player.fry_multiplier
    leela_farmer_escape_shot_hit:
        score: 2000 * current_player.leela_multiplier
    all_farmer_escape:
        score: 10000
    lunar_lander_r_shot_hit:
        score: 1000
    lunar_lander_l_shot_hit:
        score: 1000
    lunar_lander_found_shot_hit:
        score: 20000

event_player:
    timer_crate_delivery_timer_complete: end_moon_delivery
    timer_whalers_on_the_moon_timer_complete: end_moon_delivery
    timer_lunar_rover_timer_complete: end_moon_delivery
    timer_escape_farmer_timer_complete: end_moon_delivery
    timer_lunar_lander_timer_complete: end_moon_delivery
    timer_lunar_lander_found_timer_complete: end_moon_delivery
    lunar_lander_r_shot_hit: lunar_lander_searching
    lunar_lander_l_shot_hit: lunar_lander_searching
    end_moon_delivery: stop_moon_delivery_mode
    moon_delivery_success_show_ended: stop_moon_delivery_mode

widgets:
    moon_step1:
        - type: image
          image: moon_step1
          z: 5
    moon_step2:
        - type: image
          image: moon_step2
          z: 5
    moon_step3:
        - type: image
          image: moon_step3
          z: 5
    moon_step4:
        - type: image
          image: moon_step4
          z: 5
    moon_step5:
        - type: image
          image: moon_step5
          z: 5
    moon_step6:
        - type: image
          image: moon_step6
          z: 5
    moon_steps_complete:
        - type: image
          image: moon_steps_complete
          z: 5
    whalers_background:
        - type: video
          video: whalers_on_the_moon_clip
          x: 243
          y: 0
          z: 1
          anchor_x: left
          anchor_y: bottom
    rover_escape_video:
        - type: video
          video: lunar_rover_escape_clip
          z: 10
    rover_background:
        - type: video
          video: lunar_rover_clip
          x: 243
          y: 0
          z: 1
          anchor_x: left
          anchor_y: bottom
    luna_park_background:
        - type: image
          image: luna_park_background
          x: 243
          y: 0
          z: 1
          anchor_x: left
          anchor_y: bottom
    farmer_background:
        - type: video
          video: farmer_clip
          x: 243
          y: 0
          z: 1
          anchor_x: left
          anchor_y: bottom
    farmer_escape_video:
        - type: video
          video: farmer_escape_clip
          z: 10
    joyride_background:
        - type: video
          video: joyride_clip
          x: 243
          y: 0
          z: 1
          anchor_x: left
          anchor_y: bottom
    lander_background:
        - type: video
          video: lander_search_start_clip
          x: 243
          y: 0
          z: 1
          anchor_x: left
          anchor_y: bottom
    lander_found_background:
        - type: video
          video: lander_shot_lit_clip
          x: 243
          y: 0
          z: 1
          anchor_x: left
          anchor_y: bottom
    moon_delivery_success_video:
        - type: video
          video: moon_delivery_success_clip
          z: 10

sounds:
    whalers_song1:
        ducking:
            target: music
            delay: 0
            attack: 10ms
            attenuation: 1.0
            release_point: 0
            release: 10ms
    whalers_song2:
        ducking:
            target: music
            delay: 0
            attack: 10ms
            attenuation: 1.0
            release_point: 0
            release: 10ms


sound_player:
    moon_delivery_step1:
        old_moon_song:
            action: play
    deliver_crate_shot_hit:
        old_moon_song:
            action: stop
    crate_delivered_show_ended:
        old_moon_song:
            action: play
    rover_escape_shot_hit:
        old_moon_song:
            action: stop
    timer_joyride_timer_complete:
        old_moon_song:
            action: play
    play_first_whalers:
        whalers_song1:
            action: play
    play_second_whalers:
        whalers_song2:
            action: play
    s_left_loop_active: no_sound|block
    s_right_loop_active: no_sound|block
    lunar_lander_found_shot_lit:
        old_moon_song:
            action: stop
    stop_moon_delivery_mode:
        old_moon_song:
            action: stop
    ball_ending:
        old_moon_song:
            action: stop


show_player:
    mode_moon_delivery_started:
        moon_delivery_intro_show:
            loops: 0
            priority: 500
            events_when_stopped: moon_delivery_intro_show_ended
    timer_crate_delivery_timer_started:
        deliver_crate_shot_lit_show:
            loops: -1
    timer_crate_delivery_timer_stopped:
        deliver_crate_shot_lit_show: stop
    timer_crate_delivery_timer_complete:
        deliver_crate_shot_lit_show: stop
    deliver_crate_shot_hit:
        crate_delivered_show:
            loops: 0
            priority: 500
            events_when_stopped: crate_delivered_show_ended
    timer_whalers_on_the_moon_timer_started:
        whalers_shots_lit_show:
            loops: -1
    timer_whalers_on_the_moon_timer_stopped:
        whalers_shots_lit_show: stop
    timer_whalers_on_the_moon_timer_complete:
        whalers_shots_lit_show: stop
    timer_lunar_rover_timer_started:
        right_ramp_lit_show:
            loops: -1
    timer_lunar_rover_timer_stopped:
        right_ramp_lit_show: stop
    rover_escape_shot_hit:
        rover_escape_show:
            loops: 0
            events_when_stopped: rover_escape_show_ended
        right_ramp_lit_show: stop
    timer_joyride_timer_started:
        pe_platter_rotary_show:
            loops: -1
    timer_joyride_timer_stopped:
        pe_platter_rotary_show: stop
    timer_escape_farmer_timer_started:
        PEHQ_pulse_show:
            loops: -1
            priority: 500
    timer_escape_farmer_timer_complete:
        PEHQ_pulse_show: stop
    timer_escape_farmer_timer_stopped:
        PEHQ_pulse_show: stop
    all_farmer_escape:
        farmer_escape_show:
            loops: 0
            priority: 500
            events_when_stopped: farmer_escape_show_ended
    moon_delivery_step6:
        lander_r_shot_show:
            loops: -1
        lander_l_shot_show:
            loops: -1
    lunar_lander_r_shot_hit:
        lander_r_shot_show: stop
    lunar_lander_l_shot_hit:
        lander_l_shot_show: stop
    timer_lunar_lander_timer_complete:
        lander_r_shot_show: stop
        lander_l_shot_show: stop
    lunar_lander_found_shot_lit:
        lander_found_shot_show:
            loops: -1
    lunar_lander_found_shot_hit:
        lander_found_shot_show: stop
        moon_delivery_success_show:
            loops: 0
            events_when_stopped: moon_delivery_success_show_ended
    ball_ending:
        crate_delivered_show:
            action: stop
