#config_version=6
##! mode: slurm_factory

mode:
    start_events: start_slurm_factory_shot_hit
    stop_events: ball_ending, stop_slurm_factory
    priority: 105
    events_when_started: slurm_factory_tour_begins
    events_when_stopped: restart_theme_music

multiballs:
    slurm_factory_tour_MB:
      ball_count: 3
      ball_count_type: total
      shoot_again: 20s
      enable_events: mode_slurm_factory_started
      disable_events: multiball_slurm_factory_tour_MB_ended
      start_events: pure_imagination
      stop_events: timer_slurm_factory_level1_timer_complete

state_machines:
    slurm_jackpots:
        persist_state: false
        states:
            start:
                label: Start state
                events_when_started: slurm_jackpots_waiting
            level1_jackpots:
                events_when_started: slurm_factory_level1
            level2_jackpots:
                events_when_started: slurm_factory_level2
            level3_jackpots:
                events_when_started: slurm_factory_level3
            tour_complete:
                events_when_started: slurm_factory_tour_complete
        transitions:
            - source: start
              target: level1_jackpots
              events: pure_imagination
            - source: level1_jackpots
              target: level2_jackpots
              events: next_level_shot_hit
            - source: level2_jackpots
              target: level3_jackpots
              events: next_level_shot_hit
            - source: level3_jackpots
              target: tour_complete
              events: slurm_factory_final_shot_hit


timers:
    slurm_factory_release_ball_timer:
        start_value: 26
        end_value: 0
        direction: down
        control_events:
            - action: start
              event: slurm_factory_tour_begins
    slurm_factory_level1_timer:
        start_value: 125
        end_value: 0
        direction: down
        control_events:
            - action: start
              event: slurm_factory_tour_begins
            - action: stop
              event: level1_jackpots_complete
    slurm_factory_level2_timer:
        start_value: 80
        end_value: 0
        direction: down
        control_events:
            - action: start
              event: slurm_factory_level2
            - action: stop
              event: level2_jackpots_complete
    slurm_factory_level3_timer:
        start_value: 65
        end_value: 0
        direction: down
        control_events:
            - action: start
              event: slurm_factory_level3
            - action: stop
              event: level3_jackpots_complete


shots:
#advance mode levels
    next_level_shot:
        switch: s_VUK
        enable_events: level1_jackpots_complete, level2_jackpots_complete
        disable_events: next_level_shot_hit
#all levels
    left_ramp_slurp:
        switch: s_left_ramp
        enable_events: pure_imagination
#level1
    level1_right_ramp_jackpot:
        switch: s_right_ramp
        enable_events: slurm_factory_level1
        disable_events: level1_right_ramp_jackpot_hit
    level1_left_loop_jackpot:
        switch: s_left_loop
        enable_events: slurm_factory_level1
        disable_events: level1_left_loop_jackpot_hit
    level1_right_loop_jackpot:
        switch: s_right_loop
        enable_events: slurm_factory_level1
        disable_events: level1_right_loop_jackpot_hit
    level1_right_orbit_jackpot:
        switch: s_r_orbit
        enable_events: slurm_factory_level1
        disable_events: level1_right_orbit_jackpot_hit
#level2
    level2_right_ramp_jackpot:
        switch: s_right_ramp
        enable_events: slurm_factory_level2
        disable_events: level2_right_ramp_jackpot_hit
    level2_left_loop_jackpot:
        switch: s_left_loop
        enable_events: slurm_factory_level2
        disable_events: level2_left_loop_jackpot_hit
    level2_right_loop_jackpot:
        switch: s_right_loop
        enable_events: slurm_factory_level2
        disable_events: level2_right_loop_jackpot_hit
    level2_right_orbit_jackpot:
        switch: s_r_orbit
        enable_events: slurm_factory_level2
        disable_events: level2_right_orbit_jackpot_hit
#level3
    level3_right_ramp_jackpot:
        switch: s_right_ramp
        enable_events: slurm_factory_level3
        disable_events: level3_right_ramp_jackpot_hit
    level3_left_loop_jackpot:
        switch: s_left_loop
        enable_events: slurm_factory_level3
        disable_events: level3_left_loop_jackpot_hit
    level3_right_loop_jackpot:
        switch: s_right_loop
        enable_events: slurm_factory_level3
        disable_events: level3_right_loop_jackpot_hit
    level3_right_orbit_jackpot:
        switch: s_r_orbit
        enable_events: slurm_factory_level3
        disable_events: level3_right_orbit_jackpot_hit
#final shot
    slurm_factory_final_shot:
        switch: s_VUK
        enable_events: level3_jackpots_complete
        disable_events: slurm_factory_final_shot_hit


sequences:
    level1_jackpots_sequence:
        enable_events: slurm_factory_tour_begins
        events:
            - level1_right_ramp_jackpot_hit, level1_left_loop_jackpot_hit, level1_right_loop_jackpot_hit, level1_right_orbit_jackpot_hit
            - level1_right_ramp_jackpot_hit, level1_left_loop_jackpot_hit, level1_right_loop_jackpot_hit, level1_right_orbit_jackpot_hit
            - level1_right_ramp_jackpot_hit, level1_left_loop_jackpot_hit, level1_right_loop_jackpot_hit, level1_right_orbit_jackpot_hit
            - level1_right_ramp_jackpot_hit, level1_left_loop_jackpot_hit, level1_right_loop_jackpot_hit, level1_right_orbit_jackpot_hit
        events_when_complete: level1_jackpots_complete
    level2_jackpots_sequence:
        enable_events: slurm_factory_level2
        events:
            - level2_right_ramp_jackpot_hit, level2_left_loop_jackpot_hit, level2_right_loop_jackpot_hit, level2_right_orbit_jackpot_hit
            - level2_right_ramp_jackpot_hit, level2_left_loop_jackpot_hit, level2_right_loop_jackpot_hit, level2_right_orbit_jackpot_hit
            - level2_right_ramp_jackpot_hit, level2_left_loop_jackpot_hit, level2_right_loop_jackpot_hit, level2_right_orbit_jackpot_hit
            - level2_right_ramp_jackpot_hit, level2_left_loop_jackpot_hit, level2_right_loop_jackpot_hit, level2_right_orbit_jackpot_hit
        events_when_complete: level2_jackpots_complete
    level3_jackpots_sequence:
        enable_events: slurm_factory_level3
        events:
            - level3_right_ramp_jackpot_hit, level3_left_loop_jackpot_hit, level3_right_loop_jackpot_hit, level3_right_orbit_jackpot_hit
            - level3_right_ramp_jackpot_hit, level3_left_loop_jackpot_hit, level3_right_loop_jackpot_hit, level3_right_orbit_jackpot_hit
            - level3_right_ramp_jackpot_hit, level3_left_loop_jackpot_hit, level3_right_loop_jackpot_hit, level3_right_orbit_jackpot_hit
            - level3_right_ramp_jackpot_hit, level3_left_loop_jackpot_hit, level3_right_loop_jackpot_hit, level3_right_orbit_jackpot_hit
        events_when_complete: level3_jackpots_complete
variable_player:
    next_level_shot_hit:
        score: 2500 * current_player.crew_multiplier * current_player.PF_multiplier
        crew_multiplier: 1
    left_ramp_slurp_hit:
        score: (2500 * current_player.fry_multiplier) * current_player.PF_multiplier
        fry_xp: 10
    level1_right_ramp_jackpot_hit:
        score: 2500 * current_player.nibbler_multiplier * current_player.PF_multiplier
        nibbler_xp: 5
    level1_left_loop_jackpot_hit:
        score: 2500 * current_player.leela_multiplier * current_player.PF_multiplier
        leela_xp: 5
    level1_right_loop_jackpot_hit:
        score: 2500 * current_player.professor_multiplier * current_player.PF_multiplier
        professor_xp: 5
    level1_right_orbit_jackpot_hit:
        score: 2500 * (current_player.amy_multiplier + current_player.zoidberg_multiplier + current_player.hermes_multiplier) * current_player.PF_multiplier
        amy_xp: 5
        hermes_xp: 5
        zoidberg_xp: 5
    level2_right_ramp_jackpot_hit:
        score: 3500 * current_player.nibbler_multiplier * current_player.PF_multiplier
        nibbler_xp: 10
    level2_left_loop_jackpot_hit:
        score: 3500 * current_player.leela_multiplier * current_player.PF_multiplier
        leela_xp: 10
    level2_right_loop_jackpot_hit:
        score: 3500 * current_player.professor_multiplier * current_player.PF_multiplier
        professor_xp: 10
    level2_right_orbit_jackpot_hit:
        score: 3500 * (current_player.amy_multiplier + current_player.zoidberg_multiplier + current_player.hermes_multiplier) * current_player.PF_multiplier
        amy_xp: 10
        hermes_xp: 10
        zoidberg_xp: 10
    level3_right_ramp_jackpot_hit:
        score: 5000 * current_player.nibbler_multiplier * current_player.PF_multiplier
        nibbler_xp: 15
    level3_left_loop_jackpot_hit:
        score: 5000 * current_player.leela_multiplier * current_player.PF_multiplier
        leela_xp: 15
    level3_right_loop_jackpot_hit:
        score: 5000 * current_player.professor_multiplier * current_player.PF_multiplier
        professor_xp: 15
    level3_right_orbit_jackpot_hit:
        score: 5000 * (current_player.amy_multiplier + current_player.zoidberg_multiplier + current_player.hermes_multiplier) * current_player.PF_multiplier
        amy_xp: 15
        hermes_xp: 15
        zoidberg_xp: 15
    slurm_factory_final_shot_hit:
        score: 6000 * current_player.crew_multiplier * current_player.PF_multiplier
        crew_multiplier: 1
        deliveries_completed: 1

widgets:
    slurm_factory_level1_video:
        type: video
        video: slurm_factory_clip1
        z: 1
    slurm_factory_level2_video:
        type: video
        video: slurm_factory_level2_clip
        z: 1
    slurm_factory_level3_video:
        type: video
        video: slurm_factory_level3_clip
        z: 1

widget_player:
    pure_imagination:
        slurm_factory_level1_video:
            slide: slurm_factory_slide
    slurm_factory_level2:
        slurm_factory_level1_video:
            action: remove
        slurm_factory_level2_video:
            slide: slurm_factory_slide
    slurm_factory_level3:
        slurm_factory_level2_video:
            action: remove
        slurm_factory_level3_video:
            slide: slurm_factory_slide


slide_player:
    slurm_factory_tour_begins:
        slurm_factory_slide:
            target: display1
    stop_slurm_factory:
        slurm_factory_slide:
            action: remove

sound_player:
    slurm_factory_tour_begins:
        theme_full: stop

show_player:
    slurm_factory_level1:
        level1_right_ramp_jackpot_show:
            loops: -1
        level1_left_loop_jackpot_show:
            loops: -1
        level1_right_loop_jackpot_show:
            loops: -1
        level1_right_orbit_jackpot_show:
            loops: -1
        level1_gi_show:
            loops: -1
            priority: 300
    level1_right_ramp_jackpot_hit:
        level1_right_ramp_jackpot_show: stop
    level1_left_loop_jackpot_hit:
        level1_left_loop_jackpot_show: stop
    level1_right_loop_jackpot_hit:
        level1_right_loop_jackpot_show: stop
    level1_right_orbit_jackpot_hit:
        level1_right_orbit_jackpot_show: stop
    level1_jackpots_complete:
        next_level_shot_lit_show:
            loops: -1
        level1_gi_show:
            action: stop
    slurm_factory_level2:
        level1_right_ramp_jackpot_show:
            loops: -1
            speed: 1.5
        level1_left_loop_jackpot_show:
            loops: -1
            speed: 1.5
        level1_right_loop_jackpot_show:
            loops: -1
            speed: 1.5
        level1_right_orbit_jackpot_show:
            loops: -1
            speed: 1.5
        level1_gi_show:
            loops: -1
            priority: 300
            speed: 1.5
    level2_right_ramp_jackpot_hit:
        level1_right_ramp_jackpot_show: stop
    level2_left_loop_jackpot_hit:
        level1_left_loop_jackpot_show: stop
    level2_right_loop_jackpot_hit:
        level1_right_loop_jackpot_show: stop
    level2_right_orbit_jackpot_hit:
        level1_right_orbit_jackpot_show: stop
    level2_jackpots_complete:
        next_level_shot_lit_show:
            loops: -1
            speed: 1.5
        level1_gi_show:
            action: stop
#level3
    slurm_factory_level3:
        level1_right_ramp_jackpot_show:
            loops: -1
            speed: 2
        level1_left_loop_jackpot_show:
            loops: -1
            speed: 2
        level1_right_loop_jackpot_show:
            loops: -1
            speed: 2
        level1_right_orbit_jackpot_show:
            loops: -1
            speed: 2
        level1_gi_show:
            loops: -1
            priority: 300
            speed: 2
    level3_right_ramp_jackpot_hit:
        level1_right_ramp_jackpot_show: stop
    level3_left_loop_jackpot_hit:
        level1_left_loop_jackpot_show: stop
    level3_right_loop_jackpot_hit:
        level1_right_loop_jackpot_show: stop
    level3_right_orbit_jackpot_hit:
        level1_right_orbit_jackpot_show: stop
    level3_jackpots_complete:
        next_level_shot_lit_show:
            loops: -1
            speed: 2
        level1_gi_show:
            action: stop
    slurm_factory_final_shot_hit:
        next_level_shot_lit_show: stop


light_player:
    slurm_factory_tour_begins:
        loops: ffffff
        l_delivery_shot_insert: ffffff
        l_right_corner2: ffffff
        l_right_corner1: ffffff

event_player:
    timer_slurm_factory_release_ball_timer_complete: pure_imagination
    timer_slurm_factory_level1_timer_complete: stop_slurm_factory
    timer_slurm_factory_level2_timer_complete: stop_slurm_factory
    timer_slurm_factory_level3_timer_complete: stop_slurm_factory
    slurm_factory_tour_complete: stop_slurm_factory
    multiball_slurm_factory_tour_MB_ended: stop_slurm_factory
