#config_version=6
##! mode: slurm_caps

mode:
    start_events: delivery_ended, ball_started{ball!=1}
    stop_events: ball_ending, delivery_started
    priority: 101
    events_when_started: check_slurm_factory_ready

state_machines:
#this tracks if slurm factory mode is lit and relits the shot/disables other things
#on ball_start if the mode has been lit but not started yet
    slurm_factory_ready:
        persist_state: true
        states:
            start:
                label: Start state
                events_when_started: slurm_factory_not_ready
            lit:
                events_when_started: slurm_factory_is_ready
        transitions:
            - source: start
              target: lit
              events: found_golden_cap
            - source: lit
              target: start
              events: start_slurm_factory_shot_hit

shots:
    slurm_caps:
        switches: s_cap1, s_cap2, s_cap3, s_cap4
    start_slurm_factory_shot:
        switch: s_VUK
        enable_events: found_golden_cap
        disable_events: pure_imagination

ball_holds:
    slurm_factory_start_hold:
        balls_to_hold: 1
        hold_devices: bd_VUK
        enable_events: found_golden_cap
        disable_events: pure_imagination
        release_one_events: pure_imagination

variable_player:
    slurm_caps_hit:
        score: 100 * current_player.fry_multiplier * current_player.PF_multiplier
    logicblock_collecting_caps_updated:
        caps_collected:
            int: value
            action: set

counters:
    collecting_caps:
        count_events: slurm_caps_hit
        multiple_hit_window: 200ms
        persist_state: true
        count_complete_value: current_player.caps_to_golden_cap
        events_when_complete: found_golden_cap
        disable_on_complete: false
#have to reset it too... if you just use the control_events to jump to a lower
#number and starting counting again from there, it will count but won't post
#the events_when_complete
        reset_on_complete: false
        restart_events: start_slurm_factory_shot_hit

event_player:
#this relights the slurm_factory start shot when a new ball starts if the player
#lit it the last ball but didn't start it.
    check_slurm_factory_ready{current_player.caps_collected >= current_player.caps_to_golden_cap}: found_golden_cap


sound_player:
    slurm_caps_hit:
        cap_sound:
            action: play

sound_pools:
    cap_sound:
        type: random_force_all
        track: sfx
        sounds:
            - cap_sound1
            - cap_sound2
            - cap_sound3

widgets:
    slurm_cap_count:
        - type: text
          text: (slurm_caps_total)
          font_size: 400
          color: black
          z: 6
          anchor_x: center
          anchor_y: middle
    slurm_cap:
        - type: image
          image: slurm_cap
          z: 5
    glurmo_speaks:
        - type: image
          image: glurmo_speaks
          z: 10
          expire: 10s

widget_player:
    found_golden_cap:
        glurmo_speaks:
            action: add
            slide: base_slide

light_player:
    found_golden_cap:
        lamps: ffffff

show_player:
    slurm_caps_hit:
        cap_collected_show:
            loops: 0
            key: slurm_caps_indicator
    found_golden_cap:
        slurm_factory_lit_show:
            priority: 100
            loops: -1
    start_slurm_factory_shot_hit:
        slurm_factory_lit_show: stop
